@startuml

class Jugador {
    - penalizaciones : int
    - cantidadMovimientos : int
    + puntaje() : int
    + posicionDelJugador() : Posicion
    + moverse(IMovimiento, Escenario)
}

interface IMovimiento {
    + x() : int
    + y() : int
}

class Derecha {
    + x() : int
    + y() : int
}
class Arriba {
    + x() : int
    + y() : int
}
class Abajo {
    + x() : int
    + y() : int
}
class Izquierda {
    + x() : int
    + y() : int
}

class Escenario {
    - altura : int
    - anchura : int
    - matriz : IChocable
    + insertarChocable(IChocable,Posicion)
    + obtenerChocableEnPosicion(Posicion) : IChocable
    + estaDentroDelEscenario(Posicion) : Bool
}

class Posicion {
    - x : int
    - y : int
    + obtenerX() : int
    + obtenerY() : int
    + moverseDesdePosicionInicial(IMovimiento)
}

class Pozo {
    +  obtenerPuntosDePenalizacion(Moto) : int
    +  obtenerPuntosDePenalizacion(Auto) : int
    +  obtenerPuntosDePenalizacion(Todoterreno) : int
}

class Vacio {
    +  obtenerPuntosDePenalizacion(Moto) : int
    +  obtenerPuntosDePenalizacion(Auto) : int
    +  obtenerPuntosDePenalizacion(Todoterreno) : int
}

class Piquete {
    +  obtenerPuntosDePenalizacion(Moto) : int
    +  obtenerPuntosDePenalizacion(Auto) : int
    +  obtenerPuntosDePenalizacion(Todoterreno) : int
}

class Auto {
    + chocar(IChocable) : int
}

class Moto {
    + chocar(IChocable) : int
}

class Todoterreno {
    - pozosEncontrados : int
    + chocar(IChocable) : int
}

interface IVehiculo {
    + chocar(IChocable) : int
}

interface IChocable {
    + obtenerPuntosDePenalizacion(Moto) : int
    + obtenerPuntosDePenalizacion(Auto) : int
    + obtenerPuntosDePenalizacion(Todoterreno) : int
}

Jugador -> IVehiculo
IMovimiento <. Jugador

IVehiculo <|.. Auto
IVehiculo <|.. Moto
IVehiculo <|.. Todoterreno

IChocable <|.. Pozo
IChocable <|.. Vacio
IChocable <|.. Piquete

IMovimiento <|.. Arriba
IMovimiento <|.. Abajo
IMovimiento <|.. Derecha
IMovimiento <|.. Izquierda

Jugador --> Posicion
Jugador .> Escenario

Escenario --> IChocable
Escenario ..> Posicion
IMovimiento <.. Posicion
IVehiculo ..> IChocable

@enduml