@startuml
'https://plantuml.com/class-diagram

class Jugador {
    - estado : IEstado
    - nombre : string
    - posicionAnterior : Posicion
    - Escenario
    + Jugador(vehiculo, nombre)
    + mover(direccion)
    - chocarObstaculos()
    + recibirPenalizacion(penalizacion: int)
    + recibirPorcentaje(porcentaje: int)
    + cambiarVehiculo(nuevoVehiculo : Vehiculo)
    + retrocederPosicionAnterior()
    + dejarDeJugar()
    + puedeSeguirJugando()
}

abstract class Vehiculo {
    + mover(unaDireccion, unaPosicion) : Posicion
    + chocar(chocable) : IEfecto
}

class Puntaje {
    - movimientos : double
    + verMovimientos() : double
    + sumarMovimientos(cantMovimientos: int)
    + aplicarPorcentaje(porcentaje: double)
}

class Posicion {
    - x : int
    - y : int
    + Posicion(x, y)
    + equals(otraPosicion) : bool
    + x() : int
    + y() : int
    + sumarX(x: int)
    + sumarY(y: int)
    + toString() : string
}

class Direccion {
    - dirX : int
    - dirY : int
    + Direccion(dirHorizontal, dirVertical)
    + arriba() : Direccion {static}
    + abajo() : Direccion {static}
    + izquierda() : Direccion {static}
    + derecha() : Direccion {static}
    + calcularNuevaPosicion(unaPosicion) : Posicion
}

Vehiculo <-- Jugador
Jugador -> Posicion
Jugador ..> Direccion
Direccion .> Posicion
Puntaje <- Jugador

@enduml