@startuml

abstract class Vehiculo {
    + mover(unaDireccion, unaPosicion) : Posicion
    + chocar(chocable) : IEfecto
}

interface Chocable {
    + devolverEfecto(moto) : IEfecto
    + devolverEfecto(auto) : IEfecto
    + devolverEfecto(todoterreno) : IEfecto
}

interface IEfecto {
    + aplicarEfecto(jugador)
}

Vehiculo .> Chocable
Chocable ..> IEfecto

@enduml