ignore:
  - "src/main/java/edu/fiuba/algo3/controlador"
  - "src/main/java/edu/fiuba/algo3/view"
  - "src/main/java/edu/fiuba/algo3/App.java"
  - "src/main/java/edu/fiuba/algo3/Main.java"
  - "src/main/java/edu/fiuba/algo3/SystemInfo.java"
  - "src/main/java/edu/fiuba/algo3/controller"

codecov:
  token: b6716c5d-035d-4d54-9bc6-ea286aa42322