@startuml
title Un auto choca con un pozo y es penalizado con 3 movimientos
Actor usuario

"usuario" -> ":Jugador": moverse(movimiento, escenario)
":Jugador" -> ":Posicion": moverseDesdePosicionInicial(movimiento, escenario)
":Posicion" -> ":Movimiento": obtenerX()
":Posicion" -> ":Movimiento": obtenerY()
return posicionALaQueMeVoyAMover
":Posicion" --> ":Jugador": posicionALaQueMeVoyAMover
":Jugador" -> ":Escenario": obtenerElementoEnEscenario(nuevaPosicion)
":Escenario" --> ":Jugador": elementoDelEscenario
":Jugador" -> ":Auto": chocar(elementoDelEscenario)
":Auto" -> ":Pozo": obtenerPuntosDePenalizacion()
return puntosDePenalizacion
":Auto" --> ":Jugador": 3
"usuario" -> ":Jugador": movimientosRealizados()
return 2
"usuario" -> ":Jugador": totalPenalizaciones()
return 3

@enduml