@startuml
title Una moto choca con un pozo y es penalizada con 3 movimientos
Actor usuario

"usuario" -> ":Jugador": moverse(IMovimiento, escenario)
":Jugador" -> ":Posicion": moverseDesdePosicionInicial(IMovimiento, escenario)
":Posicion" -> ":IMovimiento": x()
":Posicion" -> ":IMovimiento": y()
return posicionALaQueMeVoyAMover
":Posicion" --> ":Jugador": posicionALaQueMeVoyAMover
":Jugador" -> ":Escenario": obtenerChocableEnPosicion(nuevaPosicion)
":Escenario" --> ":Jugador": IChocable
":Jugador" -> ":Moto": chocar(IChocable)
":Moto" -> ":Pozo": obtenerPuntosDePenalizacion()
return puntosDePenalizacion
":Moto" --> ":Jugador": 3
"usuario" -> ":Jugador": puntaje()
return 4

@enduml