@startuml
title Una moto choca con un piquete y es penalizado con 2 movimientos

Actor usuario

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> ":Moto": mover(direccion, posicion)
":Moto" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> ":Moto": nuevaPosicion
":Moto" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unPiquete
":Jugador" -> ":Moto": chocar(unPiquete, puntaje)
":Moto" -> ":Piquete": aplicarPenalizacion(self, puntaje)
":Piquete" -> ":Puntaje" : sumarMovimientos(2)
":Piquete" --> ":Moto" : unaMoto
":Moto" --> ":Jugador" : unaMoto

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 3
":Jugador" --> "usuario" : 3

@enduml