@startuml
title Una moto choca con un piquete y es penalizado con 2 movimientos

Actor usuario

"usuario" -> ":Jugador": moverse(IMovimiento, escenario)
":Jugador" -> ":Posicion": moverseDesdePosicionInicial(IMovimiento, escenario)
":Posicion" -> ":IMovimiento": x()
":Posicion" -> ":IMovimiento": y()
return posicionALaQueMeVoyAMover
":Posicion" --> ":Jugador": posicionALaQueMeVoyAMover
":Jugador" -> ":Escenario": obtenerChocableEnPosicion(nuevaPosicion)
":Escenario" --> ":Jugador": IChocable
":Jugador" -> ":Moto": chocar(IChocable)
":Moto" -> ":Piquete": obtenerPuntosDePenalizacion()
return puntosDePenalizacion
":Moto" --> ":Jugador": 2
"usuario" -> ":Jugador": puntaje()
return 3

@enduml