@startuml
title Una moto choca con un pozo y es penalizada con 3 movimientos
Actor usuario

"usuario" -> ":Jugador": moverse(movimiento, escenario)
":Jugador" -> ":Posicion": moverseDesdePosicionInicial(movimiento, escenario)
":Posicion" -> ":Movimiento": obtenerX()
":Posicion" -> ":Movimiento": obtenerY()
return posicionALaQueMeVoyAMover
":Posicion" --> ":Jugador": posicionALaQueMeVoyAMover
":Jugador" -> ":Escenario": obtenerElementoEnEscenario(nuevaPosicion)
":Escenario" --> ":Jugador": elementoDelEscenario
":Jugador" -> ":Moto": chocar(elementoDelEscenario)
":Moto" -> ":Pozo": obtenerPuntosDePenalizacion()
return puntosDePenalizacion
":Moto" --> ":Jugador": 3
"usuario" -> ":Jugador": movimientosRealizados()
return 1
"usuario" -> ":Jugador": totalPenalizaciones()
return 3

@enduml