@startuml
title Una 4x4 se encuentra con 3 pozos y es penalizado con 2 movimientos
Actor usuario

loop para 2 movimientos
"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> ":Todoterreno": mover(direccion, posicion)
":Todoterreno" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> ":Todoterreno": nuevaPosicion
":Todoterreno" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Jugador": chocarObstaculos()
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unPozo
":Jugador" -> ":Todoterreno": chocar(unPozo)
":Todoterreno" -> ":Pozo": devolverEfecto(self)
create ":Penalizacion"
":Pozo" --> ":Penalizacion": <<create>>
":Pozo" --> ":Todoterreno" : unaPenalizacion
":Todoterreno" --> ":Jugador" : unaPenalizacion
":Jugador" -> ":Penalizacion" : aplicarEfecto(self)
":Penalizacion" -> ":Jugador" : recibirPenalizacion(3)
":Jugador" -> ":Puntaje" : sumarMovimientos(3)
end

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> ":Todoterreno": mover(direccion, posicion)
":Todoterreno" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> ":Todoterreno": nuevaPosicion
":Todoterreno" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Jugador": chocarObstaculos()
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unPozo
":Jugador" -> ":Todoterreno": chocar(unPozo)
":Todoterreno" -> ":Pozo": devolverEfecto(self)
create ":Penalizacion"
":Pozo" --> ":Penalizacion": <<create>>
":Pozo" --> ":Todoterreno" : unaPenalizacion
":Todoterreno" --> ":Jugador" : unaPenalizacion
":Jugador" -> ":Penalizacion" : aplicarEfecto(self)
":Penalizacion" -> ":Jugador" : recibirPenalizacion(2)
":Jugador" -> ":Puntaje" : sumarMovimientos(2)

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 5
":Jugador" --> "usuario" : 5

@enduml