@startuml
title Una 4x4 atraviesa la ciudad y se encuentra con un Pozo. No es penalizada.
Actor usuario

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> ":Vehiculo": mover(direccion, posicion)
":Vehiculo" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Posicion" --> ":Jugador": posicionALaQueMeVoyAMover
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": chocable
":Jugador" -> ":Vehiculo": chocar(chocable, puntaje)
":Vehiculo" -> ":Chocable": aplicarPenalizacion(self, puntaje)
":Chocable" -> ":Vehiculo" : sumarPozo()
":Chocable" --> ":Jugador" : Vehiculo

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 1
":Jugador" --> "usuario" : 1

@enduml