@startuml
title Una 4x4 choca con una sorpresa cambio de vehículo y luego con un piquete.
Actor usuario

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> ":Todoterreno": mover(direccion, posicion)
":Todoterreno" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> ":Todoterreno": nuevaPosicion
":Todoterreno" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unaSorpresaCambioVehiculo
":Jugador" -> ":Todoterreno": chocar(unaSorpresaCambioVehiculo, puntaje)
":Todoterreno" -> ":SorpresaCambioVehiculo": aplicarPenalizacion(self, puntaje)
":SorpresaCambioVehiculo" --> ":Todoterreno" : unaMoto
":Todoterreno" --> ":Jugador" : unaMoto

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> ":Moto": mover(direccion, posicion)
":Moto" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> ":Moto": nuevaPosicion
":Moto" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unPiquete
":Jugador" -> ":Moto": chocar(unPiquete, puntaje)
":Moto" -> ":Piquete": aplicarPenalizacion(self, puntaje)
":Piquete" -> ":Puntaje" : sumarMovimientos(2)
":Piquete" --> ":Moto" : unaMoto
":Moto" --> ":Jugador" : unaMoto

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 4
":Jugador" --> "usuario" : 4

@enduml