@startuml
title Un vehículo atraviesa la ciudad y encuentra una sorpresa favorable.
Actor usuario

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> "Vehiculo": mover(direccion, posicion)
"Vehiculo" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> "Vehiculo": nuevaPosicion
"Vehiculo" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unaSorpresaFavorable
":Jugador" -> "Vehiculo": chocar(unaSorpresaFavorable, puntaje)
"Vehiculo" -> ":SorpresaFavorable": aplicarPenalizacion(self, puntaje)
":SorpresaFavorable" -> ":Puntaje" : sumarPorcentaje(-20)
":SorpresaFavorable" --> "Vehiculo" : unVehiculo
"Vehiculo" --> ":Jugador" : unVehiculo

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 0.8
":Jugador" --> "usuario" : 0.8

@enduml