@startuml
title Un vehículo atraviesa la ciudad y encuentra una sorpresa cambio de vehículo.
Actor usuario

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> "Vehiculo": mover(direccion, posicion)
"Vehiculo" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> "Vehiculo": nuevaPosicion
"Vehiculo" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unaSorpresaCambioVehiculo
":Jugador" -> "Vehiculo": chocar(unaSorpresaCambioVehiculo, puntaje)
"Vehiculo" -> ":SorpresaCambioVehiculo": aplicarPenalizacion(self, puntaje)
":SorpresaCambioVehiculo" --> "Vehiculo" : otroVehiculo
"Vehiculo" --> ":Jugador" : otroVehiculo

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 1
":Jugador" --> "usuario" : 1

@enduml