@startuml
title Un vehículo atraviesa la ciudad y encuentra una sorpresa desfavorable.
Actor usuario

"usuario" -> ":Jugador": mover(direccion, escenario)
":Jugador" -> "Vehiculo": mover(direccion, posicion)
"Vehiculo" -> ":Direccion": calcularNuevaPosicion(posicion)
":Direccion" -> ":Posicion": sumarX(dirX)
":Direccion" -> ":Posicion": sumarY(dirY)
":Direccion" --> "Vehiculo": nuevaPosicion
"Vehiculo" --> ":Jugador": nuevaPosicion
":Jugador" -> ":Puntaje": sumarMovimientos(1)
":Jugador" -> ":Escenario": obtenerChocable(nuevaPosicion)
":Escenario" --> ":Jugador": unaSorpresaDesfavorable
":Jugador" -> "Vehiculo": chocar(unaSorpresaDesfavorable, puntaje)
"Vehiculo" -> ":SorpresaDesfavorable": aplicarPenalizacion(self, puntaje)
":SorpresaDesfavorable" -> ":Puntaje" : sumarPorcentaje(25)
":SorpresaDesfavorable" --> "Vehiculo" : unVehiculo
"Vehiculo" --> ":Jugador" : unVehiculo

"usuario" -> ":Jugador": puntaje()
":Jugador" -> ":Puntaje": verMovimientos()
return 1.25
":Jugador" --> "usuario" : 1.25

@enduml